from __future__ import annotations

import json

from ara_sdk import App, invoke, schedule, scheduler

app = App("runtime-managed-schedules-demo")


def _at_to_cron(token: str) -> str:
    """Convert HH:MM to a daily 5-field cron expression."""
    raw = str(token or "").strip()
    hour_s, minute_s = raw.split(":", 1)
    hour = int(hour_s)
    minute = int(minute_s)
    if hour < 0 or hour > 23 or minute < 0 or minute > 59:
        raise ValueError("HH:MM must be within 00:00-23:59")
    return f"{minute} {hour} * * *"


def apply(*, id: str, cron: str = "", at: list[str] | None = None, timezone: str = "UTC", run: dict) -> dict:
    """
    Example-local helper that makes runtime schedule creation feel close to @app.schedule(...).
    No SDK changes required.
    """
    cron_expr = str(cron or "").strip()
    if at:
        if len(at) != 1:
            raise ValueError("apply(..., at=[...]) in this example expects exactly one HH:MM value")
        cron_expr = _at_to_cron(at[0])
    if not cron_expr:
        raise ValueError("apply(...) requires cron= or at=[HH:MM]")
    spec = schedule.cron(id=id, expr=cron_expr, timezone=timezone, run=run)
    return scheduler.create(spec)["args"]


RUNTIME_CLEANUP_CREATE_ARGS = apply(
    id="runtime-cache-cleanup-0900-utc",
    at=["09:00"],
    timezone="UTC",
    run=invoke.tool("cleanup_cache", args={"path": "/tmp/cache"}),
)


@app.tool()
def cleanup_cache(path: str = "/tmp/cache") -> dict:
    """Simple deterministic maintenance tool for a runtime-created schedule."""
    target = str(path or "").strip() or "/tmp/cache"
    return {
        "ok": True,
        "path": target,
    }


@app.agent(
    entrypoint=True,
    skills=["automation_create"],
)
def runtime_schedule_manager(input: dict) -> str:
    """
    Minimal runtime-managed scheduling example.
    No static @app.schedule declarations are defined in code.
    """
    _ = input if isinstance(input, dict) else {}
    return (
        "Create exactly one automation_create job using these args "
        "(generated by the apply(...) helper in this file):\n"
        f"{json.dumps(RUNTIME_CLEANUP_CREATE_ARGS, indent=2)}\n\n"
        "This is the fire-and-forget runtime pattern: schedule is created at runtime, "
        "not declared with @app.schedule."
    )
